<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\These;
use App\Models\Enseignant;

class TheseGestionSeeder extends Seeder
{
    public function run(): void
    {
        $theses = [

            // ── 2009 ─────────────────────────────────────────────────────
            ['nom' => 'SYLLA DOUCOURE',  'prenom' => 'Karima',              'titre' => 'Les Déterminants de la stagnation des Micro Entreprises: Analyse théorique et Etude Empirique auprès d\'un échantillon de Micro Entreprises Béninoises', 'annee' => 2009, 'option' => 'Gestion'],
            ['nom' => 'WOTO',            'prenom' => 'Théophile Magloire Adrien', 'titre' => 'Qualité perçue et confiance au sein de l\'UEMOA',            'annee' => 2009, 'option' => 'Gestion'],
            ['nom' => 'HOUNKOU',         'prenom' => 'Cossi Emmanuel',       'titre' => 'Interaction entre Pratiques de gestion, culture nationale et Performance des entreprises béninoises',                                                     'annee' => 2009, 'option' => 'Gestion'],
            ['nom' => 'GLIDJA',          'prenom' => 'Baï Judith Monique',   'titre' => 'La visibilité interorganisationnelle des cadres en Afrique de l\'Ouest: le cas du Bénin',                                                                 'annee' => 2009, 'option' => 'Gestion'],

            // ── 2010 ─────────────────────────────────────────────────────
            ['nom' => 'FATOKE',          'prenom' => 'Miftaou',              'titre' => 'Religion, ethnie et coordination des activités dans les entreprises formelles en Afrique de l\'ouest',                                                     'annee' => 2010, 'option' => 'Gestion'],

            // ── 2011 ─────────────────────────────────────────────────────
            ['nom' => 'TOGODO AZON',     'prenom' => 'Aimé',                 'titre' => 'Impact des Facteurs de contexte sur le design des systèmes de contrôle de gestion dans les collectivités locales Béninoises: une approche contingente',  'annee' => 2011, 'option' => 'Gestion'],

            // ── 2012 ─────────────────────────────────────────────────────
            ['nom' => 'ADOHINZIN',       'prenom' => 'Victor',               'titre' => 'Influence de la gouvernance d\'entreprise sur la performance et la valeur créée: Etude empirique sur les entreprises béninoises',                        'annee' => 2012, 'option' => 'Gestion'],

            // ── 2014 ─────────────────────────────────────────────────────
            ['nom' => 'HUNTON',          'prenom' => 'Mahougbé G. Mariette', 'titre' => 'Etude des pratiques socialement responsables dans la gouvernance des entreprises au Bénin',                                                              'annee' => 2014, 'option' => 'Gestion'],
            ['nom' => 'MEHOBA',          'prenom' => 'Dossa Théodore',       'titre' => 'Perception de la qualité et confiance dans le secteur de l\'enseignement supérieur privé au Bénin: Proposition d\'une échelle intégrant la satisfaction des étudiants', 'annee' => 2014, 'option' => 'Gestion'],

            // ── 2015 ─────────────────────────────────────────────────────
            ['nom' => 'AGADAME',         'prenom' => 'Ahouanadi Jean-Théophile', 'titre' => 'Profil du propriétaire-dirigeant et style de GRH dans les PME Béninoises',                                                                         'annee' => 2015, 'option' => 'Gestion'],
            ['nom' => 'AGOSSOU',         'prenom' => 'Patrice Aimé',         'titre' => 'Le management des collaborateurs de haut niveau de qualification dans les cabinets d\'audit au Bénin',                                                   'annee' => 2015, 'option' => 'Gestion'],
            ['nom' => 'HOUNDALIDJI',     'prenom' => 'Yaovi Hilaire Elvis',  'titre' => 'Structure financière et Performance des PME du secteur industriel au Bénin',                                                                             'annee' => 2015, 'option' => 'Gestion'],
            ['nom' => 'AVALLA',          'prenom' => 'H. Rubain',            'titre' => 'Les déterminants de la performance globale des Organisations publiques non marchandes en Afrique: Cas des collectivités locales Béninoises',             'annee' => 2015, 'option' => 'Gestion'],
            ['nom' => 'YESSOUFOU',       'prenom' => 'Aboudou Ramanou',      'titre' => 'Dividende, rection boursière et réputation dans le contexte culturel Africain: Etude empirique sur la bourse Régionale des valeurs mobilières',          'annee' => 2015, 'option' => 'Gestion'],
            ['nom' => 'AYENA',           'prenom' => 'Sourou Florent',       'titre' => 'Les facteurs explicatifs de l\'attachement du consommateur au point de vente traditionnel',                                                              'annee' => 2015, 'option' => 'Gestion'],
            ['nom' => 'AMIDJOGBE',       'prenom' => 'Sèvèho Thimothé Ignace', 'titre' => 'Attachement du consommateur aux médicaments contrefaits de la rue: une etude de l\'influence du comportement éthique perçu',                         'annee' => 2015, 'option' => 'Gestion'],

            // ── 2017 ─────────────────────────────────────────────────────
            ['nom' => 'DJIMALDE',        'prenom' => 'Faustin',              'titre' => 'Contrôle budgétaire et psychologie de l\'acteur: Analyse des facteurs explicatifs de comportements de réduction de la qualité des dépenses publiques Tchadiennes', 'annee' => 2017, 'option' => 'Gestion'],
            ['nom' => 'FAGNON',          'prenom' => 'Kègnidé Paulin',       'titre' => 'Le rôle modérateur du pays d\'origine sur la confiance du consommateur à l\'égard d\'un produit rumoré: cas des produits alimentaires au Bénin',        'annee' => 2017, 'option' => 'Gestion'],
            ['nom' => 'ERIOLA',          'prenom' => 'Akitola Jesse',        'titre' => 'Accès au financement et dynamisme des Petites entreprises béninoises: Manifestation des facteurs socio-culturels',                                       'annee' => 2017, 'option' => 'Gestion'],
            ['nom' => 'OGOUYOMI OROBI',  'prenom' => 'Olatundji Raoul',      'titre' => 'Influence de la consommation alimentaire sur le Bien-être du consommateur: Analyse de l\'effet modérateur des émotions',                                'annee' => 2017, 'option' => 'Gestion'],
            ['nom' => 'GBOSSOU',         'prenom' => 'Nicolas',              'titre' => 'Effet de la participation des usagers sur la gestion de la qualité des soins dans les structures de santé au Bénin',                                    'annee' => 2017, 'option' => 'Gestion'],
            ['nom' => 'DJIMSANAN',       'prenom' => 'Bacré',                'titre' => 'Implication de la responsabilité sociale d\'entreprise perçue sur le comportement de consommation socialement responsable à l\'égard des produits alimentaires', 'annee' => 2017, 'option' => 'Gestion'],
            ['nom' => 'FAKEYE',          'prenom' => 'Hubert',               'titre' => 'Valeur perçue de l\'assurance automobile et satisfaction des automobilistes au Bénin: Proposition et validation de modèle',                              'annee' => 2017, 'option' => 'Gestion'],
            ['nom' => 'SEWANOUDE',       'prenom' => 'Cosme',                'titre' => 'Difficulté financière et comportement comptables des dirigeants d\'entreprise en Afrique: cas des entreprises du Bénin',                                 'annee' => 2017, 'option' => 'Gestion'],
            ['nom' => 'IKOAFE ABADJAYE', 'prenom' => 'Mikpassè Karolle',     'titre' => 'Financement du monde rural: Analyse des expériences des institutions de microfinance avec le sous-secteur pêche au Bénin',                               'annee' => 2017, 'option' => 'Gestion'],

            // ── 2018 ─────────────────────────────────────────────────────
            ['nom' => 'DEGUENONVO',      'prenom' => 'Laurenda Marcelline',  'titre' => 'Rôle modérateur des facteurs personnels sur la relation entre le regret et les comportements post-achat du consommateur de produits de luxe contrefaits', 'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'RIBOUIS',         'prenom' => 'Toïhin Déo-Gratias',   'titre' => 'Style de management, pratique budgétaires et comportements dysfonctionnels dans les administrations publiques béninoises',                              'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'TEKPANZO',        'prenom' => 'Kpèdaton Louis',       'titre' => 'Mécanismes de création et de répartition de la richesse dans les entreprises béninoises',                                                                'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'SOGLOHOUN',       'prenom' => 'Vincent',              'titre' => 'Influence de la personnalité du magasin sur la confiance du consommateur: proposition d\'un modèle intégrateur avec effet médiateur de la proximité perçue', 'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'AMENTIEKERO',     'prenom' => 'Chalchissa',           'titre' => 'The effect of strategic orientation on innovative success: a study of small-medium enterprise in Ethiopia',                                              'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'HOUNSOUSSOU',     'prenom' => 'Yao Victor',           'titre' => 'Outils de contrôle de gestion et performance des centres hospitaliers publics du Bénin: une étude empirique',                                            'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'HOUNHUEDO',       'prenom' => 'Isidore',              'titre' => 'Mécanismes de gouvernance, personal trust et performance organisationnelle des établissements privés d\'enseignement supérieur au Bénin',                'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'IWIKOTAN',        'prenom' => 'Fidégnon Janvier',     'titre' => 'Climat des affaires, décision d\'investir et performance des entreprises: une recherche empirique dans le contexte du Bénin',                            'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'ADJIBADE',        'prenom' => 'Hervé Serge',          'titre' => 'Efficacité des mécanismes de contrôle bancaires des dirigeants par les actionnaires',                                                                   'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'ZANNOU',          'prenom' => 'Kpèdétin Philippe',    'titre' => 'Influence des pratiques de gestion sur les attitudes et comportements des salariés au travail: étude empirique appliquée aux entreprises Béninoise',     'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'FOBOSSI',         'prenom' => 'Boniface',             'titre' => 'Gouvernance et performance des institutions de microfinance dans l\'UEMOA: cas du Bénin',                                                               'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'ARINLOYE',        'prenom' => 'Armel Alphonse Afolabi Erasme', 'titre' => 'Facteurs explicatif de l\'attitude envers l\'achat des médicaments du marché parallèle: Influence de la minimisation du risque perçu et des facteurs psychologiques', 'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'DANHOUNDO',       'prenom' => 'Firmin',               'titre' => 'Pratiques de réformes administrative dans les services public au Bénin',                                                                                 'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'AGBOVOEDO',       'prenom' => '',                     'titre' => 'Influence des mécanismes de gouvernance d\'entreprise sur la relation entre la structure financière et la gestion du résultat comptable des entreprises au Bénin', 'annee' => 2018, 'option' => 'Gestion'],
            ['nom' => 'AGONHOSSOU',      'prenom' => '',                     'titre' => 'Pratiques de GRH et performance en milieux hospitalier public au au Bénin: quels rôle pour l\'inplication organisationnelle et les facteurs de contexte', 'annee' => 2018, 'option' => 'Gestion'],

            // ── 2020 ─────────────────────────────────────────────────────
            ['nom' => 'AKPAN',           'prenom' => 'Bernard',              'titre' => 'Analyse de la gouvernance de la micro assurance santé au Bénin: Organisation et mécanismes de gestion des relations entre parties prenantes',             'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'ABDALLAH HAMIL MAÏGA', 'prenom' => 'Djibrill',       'titre' => 'Responsabilité sociétale des organisations (RSO) et performance globale: Proposition d\'un modèle intégré au sein des hôpitaux',                        'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'AW SAMBA',        'prenom' => 'Ismaël Ossséni',       'titre' => 'Influence de l\'image perçue de la marque du leader sur l\'intention de vote des électeurs: le rôle de l\'éthique perçue de la marque du parti et des variables personnelles', 'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'BASSINANG',       'prenom' => 'Mamgué',               'titre' => 'Effets des déterminants de l\'attitude sur l\'intention d\'achat des marques de luxe contrefaites: rôle modérateur de la sensibilité à la marque',       'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'BAKARI',          'prenom' => 'Hadi',                 'titre' => 'Investissements communaux et responsabilité sociale au Bénin: une proposition d\'adoption des innovations responsables par les collectivités locales',    'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'ASSOGBA',         'prenom' => 'Ange Wenceslas Vinciale', 'titre' => 'L\'Influence du message RSE sur la valeur perçue de la marque par le consommateur: rôle de la congruence perçue de soi avec l\'image de la marque', 'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'HOUNYO',          'prenom' => 'Léon',                 'titre' => 'Approche comparée des performances financière et économiques d\'entreprises d\'électricité d\'Afrique subsaharienne confrontées à des restructurations ou privatisations', 'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'MOROU',           'prenom' => 'Abdou Kadiri',         'titre' => 'Congruence avec la célébrité: comment la personnalité de la marque influence l\'amour envers la marque en publicité',                                   'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'N\'DJIBIO',       'prenom' => 'Kokou Charlemagne',    'titre' => 'Audit interne et performance des administrations publiques au Bénin',                                                                                    'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'AVOCE',           'prenom' => 'Sémahon Théophile',    'titre' => 'Influence de l\'expérience écotouristique vécue sur le bien-être subjectif du consommateur: effet de la sensibilité du touriste à l\'égard de l\'environnement', 'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'SACCA BOCO',      'prenom' => 'Charles Inoussa',      'titre' => 'Financement innovant, partenariat public-privé et gouvernance des régies financières dans les pays en voie de développement: cas du Bénin',             'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'SALISSOU',        'prenom' => 'Abou',                 'titre' => 'Rôle du Contrôle dans le pilotage de la performance des universités publiques du Niger: une application des indicateurs de la responsabilité sociale des universités', 'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'VIDEROT',         'prenom' => 'Gnonnan Harry Jeer',   'titre' => 'L\'Influence de la sensibilisation environnementale sur le comportement écologique des utilisateurs de sachets plastiques: rôle des variables personnelles', 'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'YOUSOUFOU ABDOURAMANI', 'prenom' => 'Bida Nouhoume', 'titre' => 'Profil du Dirigeant, pratique de contrôle de gestion et performance des institutions de microfinance au Bénin',                                          'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'AGBOVOEDO',       'prenom' => 'Joress Sessinou',      'titre' => 'Influence des mécanismes de gouvernance d\'entreprise sur la relation entre la structure financière et la gestion du résultat comptable des entreprises au Bénin', 'annee' => 2020, 'option' => 'Gestion'],
            ['nom' => 'AGONHOSSOU',      'prenom' => 'Kindjinou Damase',     'titre' => 'Pratiques de GRH et performance en milieux hospitalier public au Bénin: quels rôle pour l\'implication organisationnelle et les facteurs de contexte',   'annee' => 2020, 'option' => 'Gestion'],

            // ── 2021 ─────────────────────────────────────────────────────
            ['nom' => 'ACAKPO',          'prenom' => 'Idohou Rachidi',       'titre' => 'La stratégie de financement de l\'entrepreneur et la réussite entrepreneuriale',                                                                         'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'AGBEDE',          'prenom' => 'O. Pierre Claver',     'titre' => 'Mécanisme de gouvernance, Externalisation de la fonction comptable et performance financière des PME au Bénin',                                          'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'IWIGNAN',         'prenom' => 'Ivan G. G.',            'titre' => 'Endettement des Petites et Moyennes Entreprises innovantes au Bénin: Facteurs explicatifs et effet sur la capacité à innover',                           'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'BOGNINOU',        'prenom' => 'Roger',                'titre' => 'Emergence de nouvelles formes d\'organisation et modes de gouvernance des filets de protection sociale dans les collectivités locales béninoises',        'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'GALLY',           'prenom' => 'Comlanvi Adolphe',     'titre' => 'Formation entrepreneuriale des dirigeants et pérénité des institutions de microfinance au Togo',                                                         'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'GNANGA',          'prenom' => 'Dothou Donatien',      'titre' => 'La performance entrepreneuriale dans l\'agro-pisciculture au Bénin',                                                                                     'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'KOUDJO',          'prenom' => 'Jean de Dieu Elisée',  'titre' => 'Innovation interactionnelle et changement organisationnel dans les services publics réticulaires',                                                       'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'LANDOZI',         'prenom' => 'Saharou',              'titre' => 'Pratique RSE et performance financière des banques au Bénin',                                                                                            'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'LAWIN',           'prenom' => 'Armand Josias',        'titre' => 'Pratiques de couverture de risque opérationnel et performance technico-économique des exploitations agricoles familiales',                               'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'LOKOSSOU',        'prenom' => 'Justin',               'titre' => 'Performance des hôpitaux publics à l\'épreuve de leur complexité organisationnelle: Rôle de contrôle de gestion',                                       'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'NOUDOHOUENOU',    'prenom' => 'Homèvo Léa Estelle',   'titre' => 'Facteurs de contingence organisationnelle et comportemental et choix des outils de contrôle de gestion dans les PME: rôle modérateur des facteurs socio-culturels', 'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'SOUNOUVOU',       'prenom' => 'D. Romaric I.',        'titre' => 'Les déterminants de l\'adoption et de l\'utilisation des services financiers mobiles au Bénin',                                                         'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'YEDJI',           'prenom' => 'Paul Dotou',           'titre' => 'Influence du comportement à l\'exportation des entreprises de la CEDEAO sur l\'utilisation des préférences commerciales chinoises: rôle du coût des règles d\'origine restrictive des biens du système commercial multilatéral', 'annee' => 2021, 'option' => 'Gestion'],
            ['nom' => 'ZINSOU',          'prenom' => 'Didier',               'titre' => 'Capital investissement et performances des PME au Bénin',                                                                                               'annee' => 2021, 'option' => 'Gestion'],

            // ── 2022 ─────────────────────────────────────────────────────
            ['nom' => 'AHLAN',           'prenom' => 'Aïmassè Iris',         'titre' => 'New public management et création de valeur dans l\'administration publique béninoise',                                                                  'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'NONKOUDJE',       'prenom' => 'Sèdjro Guillaume',     'titre' => 'Facteurs socio-culturels et dynamisme entrepreneurial des jeunes universitaires diplômés au Bénin',                                                     'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'HOUEGBENOU',      'prenom' => 'Arrèmou Florent',      'titre' => 'Influence des mécanismes de gouvernance sur la relation entre l\'apprentissage organisationnel et la performance des sociétés coopératives agricoles béninoises', 'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'MEVO',            'prenom' => 'Elie Mahougnon',       'titre' => 'Innovation managériale et performance organisationnelle des PME au Bénin',                                                                               'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'INDJENDJE NDALA', 'prenom' => 'Pierre Daniel',        'titre' => 'Intermédiation non institutielle dans une coopération entre entreprises individuelles: cas du secteur de transport',                                     'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'APLOGAN',         'prenom' => 'Joseph Edouard A.',    'titre' => 'Bien vieillir désiré et comportement de consommation des personnes âgées en perte d\'autonomie: rôle modérateur de l\'environnement social',            'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'MERE GODE',       'prenom' => 'Orou Constant',        'titre' => 'Stratégie organisationnelle et capacité d\'adaptation des coopératives agricoles dans un environnement turbulent: cas des coopératives agricoles du deuxième pôle du développement agricole au Bénin', 'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'DJIBRILA',        'prenom' => 'Abdou Kadir',          'titre' => 'Analyse des mécanismes de gestion de la souffrance des leaders des PME au Bénin',                                                                       'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'SOKEGBE',         'prenom' => 'Gérard',               'titre' => 'Mécanisme de gouvernance locale et autonomie financière des communes au Bénin',                                                                          'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'LATOUNDJI',       'prenom' => 'Folahan Médard',       'titre' => 'Coûts cachés et performance socio économique des entreprises publiques béninoises: rôle du capital humain',                                              'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'GBAGUIDI',        'prenom' => 'Mihonnougbèto Dossou Hervé', 'titre' => 'Engagement RSE et performance organisationnelle des entreprises privées de téléphonie mobile au Bénin',                                          'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'ODODE',           'prenom' => 'Adélanan Akanni Alain','titre' => 'Innovations financières et performances économiques des PME au Bénin',                                                                                  'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'ODOUNHARO',       'prenom' => 'Olachodjou Georges',   'titre' => 'Pratique de calcul des coûts et performance organisationnelle des industries au Bénin',                                                                  'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'HOUNSA',          'prenom' => 'Mahougnon Bienvenu',   'titre' => 'Système de contrôle de gestion et responsabilité sociétale des collectivités locales béninoises',                                                       'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'FALADJOU',        'prenom' => 'Iranlowo Hortense',    'titre' => 'Partenariat Public-Privé et qualité perçue de services publics du Bénin: rôle modérateur de la résistance individuelle',                               'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'GBEWEDO',         'prenom' => 'Gbodja Alain',         'titre' => 'Rôle médiateur de la confiance du consommateur sur la relation entre la proximité perçue et l\'appropriation des produits alimentaires locaux',         'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'KPEGBA',          'prenom' => 'Nancy Al-ya',          'titre' => 'Artisans organisationnels et émergence de l\'entrepreneuriat au sein des entités PME innovantes au Bénin',                                              'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'KPEGBA',          'prenom' => 'Cindy Alia',           'titre' => 'Commissariat aux comptes et efficacité du contrôle interne au sein des sociétés et offices d\'Etat au Bénin',                                          'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'AKOGNONGBE',      'prenom' => 'Romaric Miminsoa',     'titre' => 'Influence de la motivation de service public sur la performance organisationnelle au sein de l\'administration publique béninoise',                     'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'AGBANTEY',        'prenom' => 'Adébayo Samuel Destin','titre' => 'Comportement stratégique des entreprises face au lobbying des organisations non gouvernementales en matière de la responsabilité sociale de l\'entreprise au Bénin', 'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'HOUESSOU',        'prenom' => 'Kpèssou Raymond',      'titre' => 'Efficacité du contrôle interne et risque management dans les systèmes financiers décentralisés: une recherche empirique sur le rôle des pratiques de l\'occultisme au Bénin', 'annee' => 2022, 'option' => 'Gestion'],
            ['nom' => 'ISSIAKA',         'prenom' => 'Abdou Gafarou',        'titre' => 'Pratique de réseaux d\'entreprises et performance globale des PME au Bénin',                                                                           'annee' => 2022, 'option' => 'Gestion'],

            // ── 2023 ─────────────────────────────────────────────────────
            ['nom' => 'NOUGBODOHOUE',    'prenom' => 'Mahougnon Euloge A.',  'titre' => 'Pratique de responsabilité sociale des entreprises et efficacité des gestionnaires des ressources humaines dans les PME au Bénin',                      'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'DEGILA',          'prenom' => 'Guidivi-Agbo Roland Nestor', 'titre' => 'Rendement fiscal et facteur clé de succès des régis financiers dans les pays de l\'Afrique Subsaharienne',                                       'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'ADOUKONOUN GANKO','prenom' => 'M. Fabrice Octave',    'titre' => 'Analyse des déterminants de l\'adoption de la responsabilité sociétale d\'entreprise (RSE) dans les systèmes financiers décentralisés au Bénin)',       'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'YAYA SOULE KISITO','prenom' => 'Iliassou',            'titre' => 'Design organisationnel et pérénité des entreprises culturelles en contexte d\'incertitude au Bénin',                                                    'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'ACCLASSATO',      'prenom' => 'Nounagnon B. Léon',    'titre' => 'Comportement financier des gestionnaires et efficacité du contrôle budgétaire dans l\'administration publique béninoise',                               'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'KEKEREGUE',       'prenom' => 'C. Oscar',             'titre' => 'Système de contrôle de gestion et pilotage de la performance globale: rôle de la mise en œuvre de la RSE dans les universités publiques au Bénin',      'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'HESSOU',          'prenom' => 'Coffi Charles',        'titre' => 'Influence de la concurrence bancaire sur le risque crédit: rôle modérateur des mécanismes internes de gouvernance',                                     'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'TOWANOU',         'prenom' => 'Marcelin',             'titre' => 'Réforme du système éducatif et performance scolaire dans l\'enseignement secondaire au Bénin',                                                          'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'ADANGO',          'prenom' => 'Godonou Celestin',     'titre' => 'Inclusion et performance financière des petites entreprises commerciales: rôle de la digitalisation des services financiers décentralisés au Bénin',    'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'CHINCOUN',        'prenom' => 'Modeste',              'titre' => 'Profil du dirigeant et performance entrepreneuriale des startups: rôle de l\'écosystème entrepreneurial',                                               'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'AGUEGUE',         'prenom' => 'Cossi Minos Midas M.', 'titre' => 'Décisions financières et performance financière des PME du secteur Industriel au Bénin: rôle du profil du propriétaire dirigeant',                     'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'NATTA',           'prenom' => 'Gaston',               'titre' => 'Structure de propriété et performance financière des petites et moyennes entreprises au Bénin: rôle du profil du dirigeant',                           'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'DJOHOSSOU',       'prenom' => 'Agbémavo Juste Daruis','titre' => 'Influence de l\'engagement organisationnel sur les comportements innovants des salariés: rôle du bien-être au travail et des orientations vers les objectifs', 'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'ADEGNANDJOU',     'prenom' => 'Adéfemi Zacharie',     'titre' => 'Profil éthique des dirigeants et qualité de l\'information comptable et financière des PME: rôle de l\'environnement des affaires dans le contexte du Bénin', 'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'AGAMBOUE-NKANGUE','prenom' => 'Jean-Rémy',            'titre' => 'La demarche qualité "sur mesure" et son impact sur la performance organisationnel de collectivités locales: le rôle modérateur de la culture nationale',  'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'SYLLA DOUCOURE',  'prenom' => 'Bilkis',               'titre' => 'Influence du dispositif de soutien au financement bancaire de la BCEAO sur la performance des PME au Bénin',                                           'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'IKO AFE',         'prenom' => 'Codjou Edwige',        'titre' => 'Influence du climat organisationnel sur l\'activité éthique (whistleblowing) dans les entreprises publiques',                                          'annee' => 2023, 'option' => 'Gestion'],
            ['nom' => 'KARIFENE',        'prenom' => 'Ali',                  'titre' => 'Influence de la gestion des compétences sur la performance des PME tchadiennes',                                                                        'annee' => 2023, 'option' => 'Gestion'],

            // ── 2024 ─────────────────────────────────────────────────────
            ['nom' => 'AKE',             'prenom' => 'Natondé',              'titre' => 'Management des établissements privés et qualité de l\'enseignement supérieur au Bénin',                                                                  'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'DOSSOU',          'prenom' => 'Tonankpon Désiré Samson', 'titre' => 'Profit du dirigeant et gestion du résultat comptable dans les grandes entreprises au Bénin : Rôle du mode de financement',                          'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'BAIMEY',          'prenom' => 'Dèwanou Claude',       'titre' => 'Système de contrôle de Gestion et performance opérationnelle des organisations',                                                                        'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'SERO',            'prenom' => 'Ahmed',                'titre' => 'Gestion de l\'intérim et performance sociale des entreprises au Bénin: Rôle du contrat Psychologique',                                                  'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'HOUANSOU',        'prenom' => 'Sètchémin Noudéhougbè Mesmin', 'titre' => 'Influence des avertissements sanitaires alcool sur l\'intention de consommer des jeunes au Bénin: Rôle modérateur de l\'invulnérabilité perçue', 'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'SOHOUNHLOUE',     'prenom' => 'Jean-Gildert Agbélé', 'titre' => 'Analyse de l\'influence de l\'agencification des structures étatiques sur la qualité du service public au Bénin',                                      'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'GODJO',           'prenom' => 'Ehuzu Herman',         'titre' => 'Profit du dirigeant, Comportement financier et performance financière des PME au Bénin',                                                               'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'HANGNOUN',        'prenom' => 'Ernest',               'titre' => 'Les déterminants de l\'investissement et l\'attractivité des collectivités locales au Bénin: Rôle modérateur du comportement des élus locaux',          'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'SOARES',          'prenom' => 'Roselyn Armel',        'titre' => 'Pratiques de Succession et pérennité des petites et moyennes entreprises familiales au Bénin',                                                         'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'AHOUANDJINOU',    'prenom' => 'Sylvain',              'titre' => 'Détresse financière et performance organisationnelle des petites et moyenne entreprises au Bénin: Rôle du comportement du Dirigeant',                   'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'AGBANNOU',        'prenom' => 'Coffi Casimir Thierry','titre' => 'Le rôle de la motivation entrepreneuriale dans la relation entre le capital humain de l\'entrepreneur dirigeant et la réussite entrepreneuriale',       'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'HEMADOU',         'prenom' => 'Elie',                 'titre' => 'Mécanisme de gouvernance et compétitivité: Rôle de l\'agilité organisationnelle des PME de la zone industrielle Glo-Djigbé au Bénin',                  'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'LANKPOKINTO',     'prenom' => 'Donatien',             'titre' => 'Les facteurs clés de succès d\'implantation des outils modernes de pratique de coûts dans les entreprises au Bénin',                                   'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'SEWANOUDE',       'prenom' => 'Damien',               'titre' => 'Pratiques RSE et performance financière des Petites et Moyennes Entreprises béninoise: Rôle de la culture organisationnelle',                           'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'OSSENI',          'prenom' => 'Choukourath-Laï Abédjè A.T.', 'titre' => 'Influence de la persuasion par la peur sur la résistance du consommateur au Bénin: Rôle modérateur de la transmission des valeurs à l\'égard de l\'utilisation des sachets plastiques', 'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'TCHOWOUI',        'prenom' => 'Pierre',               'titre' => 'Etude des déterminants de coopération entre contrôleur de gestion et responsables opérationnels dans les grandes entreprises au Bénin',                'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'LANMATCHION',     'prenom' => 'Epiphane Bidossessi',  'titre' => 'Gouvernance des établissements secondaires publics et performance scolaire au Bénin: Rôle du soutien parental',                                        'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'AHOSSIN',         'prenom' => 'Elvis Franck Modeste', 'titre' => 'Déterminants de la viabilité des entreprises Agricoles au Bénin: Cas des jeunes entrepreneures Agricoles du département de l\'Atlantique',             'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'LOKOSSOU',        'prenom' => 'Enagnon Hermann',      'titre' => 'Pratiques de Responsabilité Sociale des Entreprises et Performance Globale des exploitations agricoles au Bénin',                                      'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'MENGUE BIYOGHO',  'prenom' => 'Agnès Urielle',        'titre' => 'Perception de l\'Orientation entrepreneuriale de l\'université et intention entrepreneuriale des étudiants: Rôle modérateur de l\'exposition à l\'entrepreneuriat', 'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'ABOMO ONANA',     'prenom' => 'Carine Dolores',       'titre' => 'Diversité culturelle, performance de l\'équipe au travail et création de valeur des PME au Cameroun: Une étude appliquée au secteur tertiaire',         'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'KONAN',           'prenom' => 'Amani Tatiana',        'titre' => 'Culture nationale et investissement socialement responsable à la Bourse Régionale des Valeurs Mobilières: Une étude à partir du cas de la Côte d\'Ivoire', 'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'KEPNDIP',         'prenom' => 'Judith Kahiéle',       'titre' => 'Proximité et accès au financement bancaire des femmes propriétaires-dirigeantes des Petites et Moyennes Entreprises: Rôle modérateur du profit de la dirigeante', 'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'ASSIH',           'prenom' => 'Kéméalo',              'titre' => 'Mécanisme de gouvernance et accès au financement des exploitations agricoles au Bénin: Rôle du profit du dirigeant',                                   'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'AGNONVI',         'prenom' => 'Sika',                 'titre' => 'Système de contrôle de gestion et performance socio-économique des collectivités territoriales au Togo: Rôle de la participation citoyenne',             'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'OWOLABI',         'prenom' => 'Miyissé Espérance Prisca', 'titre' => 'Influence des composantes du style parental sur le comportement alimentaire ses enfants: Rôle modérateur de la résilience parentale',              'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'SINABA',          'prenom' => 'Kandia',               'titre' => 'Gouvernance de la transformation numérique et mobilisation des recettes fiscales au Bénin',                                                             'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'KAMTCHUENG',      'prenom' => 'Johanne',              'titre' => 'Fidélisation des employés de la génération Z dans les établissements privés d\'enseignement secondaire au Cameroun',                                    'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'BECOIN',          'prenom' => 'Adjoua Annick-Emma',   'titre' => 'Analyse des déterminants de la résiliance des PME face à la crise sanitaire liée à la COVID-19 en Côte d\'Ivoire',                                     'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'POUDEMABIYA',     'prenom' => 'Pnawélé',              'titre' => 'Rôle médiateur de l\'attrait des sponsors entre les pratiques marketing des clubs sportifs béninois et leurs réputations perçues',                      'annee' => 2024, 'option' => 'Gestion'],
            ['nom' => 'GAGA',            'prenom' => 'Alice Adélaïde',       'titre' => 'Pratiques du contrôle de gestion dans les entreprises publiques béninoises: Influence des facteurs socioculturels',                                     'annee' => 2024, 'option' => 'Gestion'],

            // ── 2025 ─────────────────────────────────────────────────────
            ['nom' => 'ABDOULAYE',       'prenom' => 'Leïla Fatima',         'titre' => 'Influence du Management universitaire sur l\'efficacité externe de la formation au Cameroun: Etude des pratiques d\'accompagnement',                    'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'ADIKPETO G.',     'prenom' => 'Hospice',              'titre' => 'Compétences sociales du propriétaire dirigeant et émergence des PME au Bénin: Rôle du capital social',                                                  'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'ADISSO A.',       'prenom' => 'Nestor',               'titre' => 'Mécanismes de la coproduction de services publics de base dans les collectivités locales béninoises',                                                   'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'AGOSSA',          'prenom' => 'Georges',              'titre' => 'Influence des Mécanismes de Contrôle sur les risques de fraudes en contexte dématérialisé: Une Analyse Empirique dans l\'Administration Fiscale au Bénin', 'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'AHOLOU',          'prenom' => 'Sidouane',             'titre' => 'Influence du parrainage du football sur la perception des actions RSE d\'une marque sponsor: Rôle modérateur de la durée du parrainage',                'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'AHOMLANTO',       'prenom' => 'Georges',              'titre' => 'Influence de la valeur perçue sur l\'adhésion des consommateurs au marketing à paliers multiples: Rôle modérateur des leaders d\'opinion',              'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'AHOTONDJI',       'prenom' => 'Yessia Eric Edmond',   'titre' => 'Business modèle et la performance financière des banques au Bénin: Une analyse de la taille de la banque et la part du marché',                        'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'COUTHON',         'prenom' => 'Hervé Raoul',          'titre' => 'Style de management et succès des projets innovants dans les organisations publiques au Bénin',                                                         'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'DAGNONHOUETON',   'prenom' => 'Zacharie Euloge Rostand Daroze', 'titre' => 'New public management et performance organisationnelle du réseau d\'alimentation en eau potable au Bénin',                                   'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'DOSSOU',          'prenom' => 'Yannick Stanislas Gbètondji', 'titre' => 'Pratiques de Contrôle de Gestion et performance organisationnelle des établissements publics de formation et de recherche au Bénin: Influence du profil du contrôleur de gestion', 'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'EBO',             'prenom' => 'Marc Coomlan Emmanuel','titre' => 'Financement participatif et réussite des agripreneurs dans le contexte béninois: Une analyse du rôle de l\'accompagnement entrepreneurial en post création', 'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'EDISSA',          'prenom' => 'Waliou',               'titre' => 'Mécanismes de gouvernance des PME familiales béninoises et performance financière: rôle du profil du dirigeant',                                        'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'ELEGBE',          'prenom' => 'Ahoga Bernard',        'titre' => 'Microfinance islamique et performance sociale des systèmes financiers décentralisés au Bénin: Analyse exploratoire par étude de cas',                    'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'ENIANLOKO',       'prenom' => 'Codjo Aristide Sébastien', 'titre' => 'Structure de propriété et performance organisationnelle des entreprises hôtelières au Bénin',                                                      'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'FADONOUGBO',      'prenom' => 'Jean Pierre A. Cossi', 'titre' => 'Le rôle de l\'Etat dans la relation entre les innovations managériales et la compétitivité de la filière ananas au Bénin',                             'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'FAIZOUN',         'prenom' => 'Mahugnon Thècle',      'titre' => 'Gouvernance locale et éfficacité du contrôle interne dans les collectivités territoriales décentralisées au Bénin',                                     'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'FANOU',           'prenom' => 'Sévérin',              'titre' => 'Pratiques RSE et pérennité des petites et moyennes entreprises au Bénin: Rôle des facteurs socio-culturel',                                             'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'GANFON',          'prenom' => 'Juste Patient Ahoyia', 'titre' => 'Influence du logo du parti sur le comportement des électeurs: Rôle de la personnalité du leader du parti politique',                                   'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'HINVI',           'prenom' => 'Rock Stanislas',       'titre' => 'Capital humain et performance organisationnelle des entreprises publiques béninoises: Rôle des variables socio-démographiques',                         'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'HOUESSOU',        'prenom' => 'Sègla Steeweel Kossi James', 'titre' => 'Eco innovation et avantages concurrentiels durables: une étude sur les petites et moyennes entreprises béninoises du secteur agro-alimentaire', 'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'HOUNDAKPO',       'prenom' => 'Honoré Romaric',       'titre' => 'Mécanismes de gouvernance d\'entreprises et performance financière des PME au Bénin: Rôle du système d\'information comptable',                        'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'HOUNDEMIKON',     'prenom' => 'Dossavi Marcellin',    'titre' => 'Pratiques de la géomancie Fâ et processus de prise de décision des dirigeants des PME au Bénin',                                                      'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'HOUNGBEDJI',      'prenom' => 'Houénafa Laurent',     'titre' => 'Influence des valeurs environnementales et de la préoccupation pour l\'environnement sur les comportements d\'achats verts: Rôle du médiateur et la confiance verte', 'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'KEGNIDE',         'prenom' => 'Mahutin Christophe',   'titre' => 'Les leviers d\'accès au financement formel de l\'entrepreneuriat féminin au Bénin',                                                                    'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'LAWANI',          'prenom' => 'Abdel Wahidh',         'titre' => 'Influence de l\'orientation marché sur la performance commerciale du musé d\'art contemporain: Rôle modérateur de la préoccupation pour l\'environnement du visiteur', 'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'SOUROU',          'prenom' => 'Ernest Cyrille Ayadji','titre' => 'Décision d\'externalisation de la fonction d\'audit interne, qualité de l\'auditeur et performance financière des entités publiques à caractère commercial et industriel au Bénin', 'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'WOTO',            'prenom' => 'Tété Sognicaca Francine','titre' => 'Professionnalisation des clubs de football et performance sportive au Bénin: Le rôle du profil du coach sportif',                                   'annee' => 2025, 'option' => 'Gestion'],
            ['nom' => 'YENONFAN',        'prenom' => 'Ruffin',               'titre' => 'Digitalisation et performance commerciale des PME béninoises : Rôle du dirigeant',                                                                     'annee' => 2025, 'option' => 'Gestion'],
        ];

        foreach ($theses as $data) {
            These::create([
                'titre'           => $data['titre'],
                'statut'          => 'soutenue',
                'publiee'         => true,
                'date_soutenance' => \Carbon\Carbon::create($data['annee'], 6, 30),
                'mot_cles'        => 'gestion, PME, Bénin, performance, gouvernance',
                'directeur_id'    => null,
                'doctorant_id'    => null,
                'jury'            => null,
                'resume'          => null,
            ]);
        }

        $this->command->info(count($theses) . ' thèses en Gestion créées avec succès.');
    }
}

